(()=>{'use strict';
const SUPABASE_URL='https://ltehjhvxrnwatbqplmxr.supabase.co';
const SUPABASE_KEY='sb_publishable_GwgM9WAAvVGwNxUQEFf9yQ_YDWbI0xa';
const API=SUPABASE_URL+'/functions/v1/commercialisation-api';
let client;
const $=id=>document.getElementById(id);
const esc=s=>String(s??'').replace(/[&<>"']/g,m=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[m]));
function loadLib(){return new Promise(resolve=>{if(window.supabase)return resolve();const s=document.createElement('script');s.src='https://cdn.jsdelivr.net/npm/@supabase/supabase-js@2';s.onload=resolve;s.onerror=resolve;document.head.appendChild(s)})}
async function init(){await loadLib();if(!window.supabase)return;client=window.supabase.createClient(SUPABASE_URL,SUPABASE_KEY);buildUI();await refresh()}
function buildUI(){if($('ce-auth-style'))return;const st=document.createElement('style');st.id='ce-auth-style';st.textContent='.ce-auth-btn{border:0!important;background:#103c2c!important;color:#fff!important;border-radius:10px!important;padding:10px 14px!important;font-weight:900!important;cursor:pointer}.ce-auth-overlay{position:fixed;inset:0;background:#07130ecc;z-index:99999;display:none;align-items:center;justify-content:center;padding:18px}.ce-auth-modal{background:#fff;border-radius:18px;max-width:520px;width:100%;padding:22px;box-shadow:0 20px 60px #0005}.ce-auth-modal input,.ce-auth-modal select{margin-bottom:10px}.ce-auth-actions{display:grid;gap:8px;margin-top:10px}.ce-auth-close{float:right;border:0;background:none;font-size:24px;cursor:pointer}.ce-auth-msg{padding:10px;border-radius:10px;background:#e8f4ed;margin:10px 0;font-size:14px}.ce-auth-danger{background:#fff0f0;color:#8d2222}.ce-account-panel{margin-top:12px;padding:14px;border:1px solid var(--line);border-radius:12px;background:var(--soft)}';document.head.appendChild(st);
const h=document.querySelector('header');if(h&&!$('ce-auth-open')){const b=document.createElement('button');b.id='ce-auth-open';b.className='ce-auth-btn';b.textContent='Compte / Connexion';b.onclick=()=>openAuth();h.appendChild(b)}
const o=document.createElement('div');o.id='ce-auth-overlay';o.className='ce-auth-overlay';o.innerHTML='<div class="ce-auth-modal"><button class="ce-auth-close" id="ce-auth-close">×</button><h2 id="ce-auth-title">Compte Chiffr’EcoPro</h2><div id="ce-auth-body"></div></div>';document.body.appendChild(o);$('ce-auth-close').onclick=()=>o.style.display='none';o.addEventListener('click',e=>{if(e.target===o)o.style.display='none'});}
async function refresh(){const {data:{session}}=await client.auth.getSession();const b=$('ce-auth-open');if(b)b.textContent=session?'Mon compte':'Compte / Connexion';if(session){try{const r=await fetch(API+'/subscription-state',{method:'POST',headers:{Authorization:'Bearer '+session.access_token,'Content-Type':'application/json'}});window.ceCommercialState=await r.json()}catch{window.ceCommercialState=null}}}
function openAuth(){const o=$('ce-auth-overlay');if(!o)return;o.style.display='flex';renderAuth()}
function renderAuth(){client.auth.getSession().then(({data:{session}})=>{const body=$('ce-auth-body');if(session){const s=window.ceCommercialState||{};body.innerHTML='<p><b>Connecté :</b> '+esc(session.user.email||'')+'</p><div class="ce-account-panel"><b>Offre :</b> '+esc(s.plan||'Aucune')+'<br><b>Évaluations gratuites :</b> '+(s.evaluations_remaining??3)+'/3<br><b>Statut :</b> '+esc(s.subscription_status||'none')+'<br><b>Vérification PRO :</b> '+esc(s.professional_verification_status||'not_started')+'</div><div class="ce-auth-actions"><button class="primary" id="ce-buy-part">Souscrire Particulier — 2,99 €/mois</button><button id="ce-buy-pro">Souscrire Professionnel — 9,99 €/mois</button>'+(s.plan?'<button id="ce-portal">Gérer mon abonnement</button>':'')+'<button id="ce-logout">Se déconnecter</button></div>'+(s.professional_verification_status!=='verified'?'<div class="ce-account-panel"><h3>👷 Activation professionnelle</h3><p class="muted">Pour accéder au tarif PRO, envoyez un justificatif professionnel. Votre demande sera vérifiée avant l’abonnement.</p><label>SIRET / référence</label><input id="ce-pro-ref" inputmode="numeric" placeholder="SIRET (facultatif)"><label>Justificatif</label><input id="ce-pro-doc" type="file" accept=".pdf,.jpg,.jpeg,.png"><button class="primary" id="ce-pro-submit">Envoyer le justificatif</button><div id="ce-pro-msg"></div></div>':'<div class="ce-account-panel"><b>✓ Profil professionnel vérifié.</b><p class="muted">Vous pouvez souscrire à l’offre PRO.</p></div>')+'<p class="muted">Le compte est nécessaire pour enregistrer les évaluations et l’abonnement.</p>';$("ce-buy-part").onclick=()=>checkout('particulier');$("ce-buy-pro").onclick=()=>checkout('professionnel');if($("ce-portal"))$("ce-portal").onclick=()=>customerPortal();if($("ce-pro-submit"))$("ce-pro-submit").onclick=()=>submitProfessionalVerification();$("ce-logout").onclick=async()=>{await client.auth.signOut();await refresh();renderAuth()};return}body.innerHTML='<p>Créez votre compte ou connectez-vous pour utiliser les évaluations gratuites et les offres.</p><label>Email</label><input id="ce-email" type="email" autocomplete="email" placeholder="vous@exemple.fr"><label>Mot de passe</label><input id="ce-password" type="password" autocomplete="new-password" placeholder="6 caractères minimum"><div class="ce-auth-actions"><button class="primary" id="ce-signup">Créer mon compte</button><button id="ce-login">Se connecter</button></div><div id="ce-auth-msg"></div>';$('ce-signup').onclick=()=>signup();$('ce-login').onclick=()=>login()})}
async function signup(){const email=$('ce-email').value.trim(),password=$('ce-password').value;if(!email||password.length<6)return msg('Email et mot de passe (6 caractères minimum) requis',true);const {data,error}=await client.auth.signUp({email,password});if(error)return msg(error.message,true);if(data.session){await refresh();renderAuth()}else msg('Compte créé. Vérifiez votre email si la confirmation est demandée, puis connectez-vous.')} 
async function login(){const email=$('ce-email').value.trim(),password=$('ce-password').value;const {data,error}=await client.auth.signInWithPassword({email,password});if(error)return msg(error.message,true);await refresh();renderAuth()}
function msg(t,bad){const e=$('ce-auth-msg');if(e){e.className=bad?'ce-auth-msg ce-auth-danger':'ce-auth-msg';e.textContent=t}}
async function customerPortal(){const {data:{session}}=await client.auth.getSession();if(!session)return openAuth();const r=await fetch(API+'/customer-portal',{method:'POST',headers:{Authorization:'Bearer '+session.access_token,'Content-Type':'application/json'}});const d=await r.json();if(!r.ok){msg(d.error||'Impossible d’ouvrir la gestion de l’abonnement',true);return}if(d.portal_url)location.href=d.portal_url}
async function submitProfessionalVerification(){const f=$('ce-pro-doc')?.files?.[0],ref=$('ce-pro-ref')?.value?.trim()||'';const out=$('ce-pro-msg');if(!f){if(out)out.textContent='Sélectionnez un justificatif.';return}if(f.size>10*1024*1024){if(out)out.textContent='Fichier trop volumineux (10 Mo maximum).';return}const allowed=['application/pdf','image/jpeg','image/png'];if(!allowed.includes(f.type)){if(out)out.textContent='Formats acceptés : PDF, JPG ou PNG.';return}const {data:{session}}=await client.auth.getSession();if(!session)return openAuth();if(out)out.textContent='Préparation de l’envoi…';const r=await fetch(API+'/professional-verification/upload-url',{method:'POST',headers:{Authorization:'Bearer '+session.access_token,'Content-Type':'application/json'},body:JSON.stringify({type:'justificatif_professionnel',reference:ref,file_name:f.name})});const d=await r.json();if(!r.ok){if(out)out.textContent=d.error||'Impossible de préparer l’envoi.';return}const up=await client.storage.from('cc-professional-docs').uploadToSignedUrl(d.storage_path,d.token,f,{contentType:f.type,upsert:false});if(up.error){if(out)out.textContent=up.error.message||'Échec de l’envoi.';return}if(out)out.textContent='✓ Justificatif envoyé. Vérification en attente.';await refresh();setTimeout(renderAuth,300)}
async function checkout(plan){const {data:{session}}=await client.auth.getSession();if(!session)return openAuth();const r=await fetch(API+'/create-checkout-session',{method:'POST',headers:{Authorization:'Bearer '+session.access_token,'Content-Type':'application/json'},body:JSON.stringify({plan})});const d=await r.json();if(!r.ok){msg(d.error||'Impossible de créer le paiement',true);return}location.href=d.checkout_url}
async function consume(){const {data:{session}}=await client.auth.getSession();if(!session){openAuth();return false}const r=await fetch(API+'/consume-evaluation',{method:'POST',headers:{Authorization:'Bearer '+session.access_token,'Content-Type':'application/json'}});const d=await r.json();if(!r.ok){if(d.code==='FREE_EVALUATIONS_EXHAUSTED'){openAuth();msg('Les 3 évaluations gratuites sont utilisées. Choisissez une offre.',true);return false}msg(d.error||'Évaluation impossible',true);return false}window.ceCommercialState=d;return true}
const oldEstimate=window.estimate;window.estimate=async()=>{if(!(await consume()))return;if(typeof oldEstimate==='function')oldEstimate()};
window.ceAuth={open:openAuth,refresh,checkout,consume}; 
if(document.readyState==='loading')document.addEventListener('DOMContentLoaded',()=>setTimeout(init,500),{once:true});else setTimeout(init,500);
})();