(()=>{
'use strict';
const $=id=>document.getElementById(id);
const money=n=>new Intl.NumberFormat('fr-FR',{style:'currency',currency:'EUR'}).format(Number(n)||0);
function brand(){document.title='Chiffr’EcoPro — V31';document.querySelectorAll('.logo').forEach(x=>x.textContent='Chiffr’EcoPro');document.querySelectorAll('.pill').forEach(x=>{if(x.textContent.includes('VERSION 6'))x.textContent='VERSION 31'});}
function addBarometer(){if($('ecoBarometer')||!$('res'))return;const card=document.createElement('div');card.id='ecoBarometer';card.className='card';card.innerHTML='<h2>📊 Baromètre de cohérence PRO</h2><div class="grid3"><div class="box"><div class="muted">Niveau</div><div id="baroLevel" class="big">—</div></div><div class="box"><div class="muted">Indice</div><div id="baroScore" class="score" style="font-size:34px">—</div>/100</div><div class="box"><div class="muted">Fourchette</div><div id="baroRange" class="big">—</div></div></div><p id="baroText" class="muted"></p><p class="muted">Indice d’aide à la décision : il ne remplace pas les prix locaux, les coûts réels ni une consultation professionnelle.</p>';$('res').parentNode.insertBefore(card,$('res'));}
function barometer(d){if(!$('baroScore')||!d)return;let s=50,notes=[];const q=+($('qty')?.value||0),h=+(d.hours||0),w=(d.wastes||[]).reduce((a,x)=>a+(+x.v||0),0),difficulty=$('etat')?.value||'';if(/difficile|dégradé|friche|envahi|danger|accès/i.test(difficulty)){s+=12;notes.push('contraintes de chantier')}if(q>0&&q<2){s+=5;notes.push('petite quantité')}if(h>=8){s+=5;notes.push('durée importante')}if(w>0){s+=8;notes.push('évacuation intégrée')}if($('sort')?.checked){s+=5;notes.push('tri proposé')}if($('reuse')?.checked){s+=5;notes.push('réemploi recherché')}if($('grind')?.checked){s+=3;notes.push('broyage possible')}if($('opt')?.checked){s+=4;notes.push('déplacements optimisés')}s=Math.max(0,Math.min(100,s));let level='Vert — cohérent',mult=.92;if(s<40){level='Rouge — à vérifier';mult=.82}else if(s<55){level='Orange — prudence';mult=.87}else if(s<70){level='Jaune — à comparer';mult=.92}else if(s>=85){level='Vert — très cohérent';mult=.98}const lo=d.ht*mult,hi=d.ht*(2-mult);$('baroScore').textContent=s;$('baroLevel').textContent=level;$('baroRange').textContent=money(lo)+' → '+money(hi);$('baroText').textContent=notes.length?'Facteurs détectés : '+notes.join(' · ')+'.':'Aucun facteur inhabituel détecté.';}
function addEvacuationDistance(){const card=$('wt')?.closest('.card');if(!card||$('wdistance'))return;const p=card.querySelector('p');const row=document.createElement('div');row.className='grid3';row.innerHTML='<div><label>Distance aller-retour (km)</label><input id="wdistance" type="number" min="0" step="0.1" placeholder="Ex. 24"></div><div><label>Coût transport €/km</label><input id="wkmcost" type="number" min="0" step="0.01" value="1.20"></div><div><label>Type de trajet</label><select id="wtrip"><option>Camion / benne</option><option>Utilitaire</option><option>Remorque</option></select></div>';p.insertAdjacentElement('beforebegin',row);}
function init(){brand();addBarometer();addEvacuationDistance();const old=window.addWaste;if(old&&!window.__v15){window.__v15=true;window.addWaste=function(){const before=(window.wastes||[]).length;old.apply(this,arguments);const arr=window.wastes||[];if(arr.length>before){const x=arr[arr.length-1],km=+$('wdistance')?.value||0,kc=+$('wkmcost')?.value||0;if(km>0&&kc>0){x.transport=km*kc;x.c+=x.transport;if(window.wasteRender)window.wasteRender();}if($('wdistance'))$('wdistance').value='';if($('wkmcost'))$('wkmcost').value='1.20';}};}
const oldCalc=window.calc;if(oldCalc&&!window.__v15calc){window.__v15calc=true;window.calc=function(){const d=oldCalc.apply(this,arguments);try{barometer(d)}catch(e){}return d};}
}
if(document.readyState==='loading')document.addEventListener('DOMContentLoaded',init);else init();
})();
