(()=>{
'use strict';
const $=id=>document.getElementById(id);
const esc=s=>String(s??'').replace(/[&<>"']/g,m=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[m]));
const eur=v=>Number(v||0).toLocaleString('fr-FR',{style:'currency',currency:'EUR'});
const load=(k,d=[])=>{try{return JSON.parse(localStorage.getItem(k)||JSON.stringify(d))}catch(_){return d}};
const save=(k,v)=>localStorage.setItem(k,JSON.stringify(v));
const nextNumber=(key,prefix)=>{const y=new Date().getFullYear();const seq=load(key,{});seq[y]=(seq[y]||0)+1;save(key,seq);return `${prefix}-${y}-${String(seq[y]).padStart(3,'0')}`};

function snapshot(){
  const rows=(id)=>[...document.querySelectorAll(`#${id} .item`)].map(x=>x.innerText.trim());
  const flags=['sort','reuse','grind','opt'].reduce((a,k)=>{a[k]=!!$(k)?.checked;return a},{});
  const quote={
    entreprise:$('entreprise')?.value||'',client:$('client')?.value||'',metier:$('metier')?.value||'',prest:$('prest')?.value||'',etat:$('etat')?.value||'',
    qty:+($('qty')?.value||0),unit:$('unit')?.value||'',hours:+($('hours')?.value||0),rate:+($('rate')?.value||0),vat:+($('vat')?.value||0),
    direct:$('cost')?.textContent||'0 €',margin:$('me')?.textContent||'0 €',marginPct:$('mr')?.textContent||'0 %',ht:$('ht')?.textContent||'0 €',ttc:$('ttc')?.textContent||'0 €',
    materials:rows('ml'),tools:rows('tl'),wastes:rows('wlst'),eco:flags,date:new Date().toLocaleString('fr-FR')
  };
  return quote;
}
function ensureNumber(){let n=$('num')?.value?.trim();if(!n){n=nextNumber('ce_doc_sequences','DEV');if($('num'))$('num').value=n}return n}
function baseCss(){if($('ce-docs-style'))return;const s=document.createElement('style');s.id='ce-docs-style';s.textContent=`
.ce-docbar{display:flex;gap:8px;flex-wrap:wrap;margin-top:12px}.ce-docbar button{padding:10px 13px;border:1px solid var(--line,#d8e3dd);border-radius:9px;background:#fff;font-weight:800;cursor:pointer}.ce-doc-card{background:#fff;border:1px solid var(--line,#d8e3dd);border-radius:15px;padding:18px;margin-bottom:16px}.ce-doc-toolbar{display:flex;gap:8px;flex-wrap:wrap;align-items:center;margin-bottom:12px}.ce-doc-list .item{display:grid;grid-template-columns:1fr auto;gap:8px}.ce-doc-sub{font-size:13px;color:var(--muted,#64736b)}.ce-doc-good{background:#e7f6ec;border:1px solid #bddfc8;padding:10px;border-radius:9px}.ce-doc-warn{background:#fff5d6;border:1px solid #eed47b;padding:10px;border-radius:9px}.ce-doc-print{max-width:850px;margin:auto;background:#fff;padding:28px;border:1px solid #ddd}.ce-doc-print h1{text-align:center}.ce-doc-grid{display:grid;grid-template-columns:repeat(2,minmax(0,1fr));gap:10px}@media(max-width:560px){.ce-doc-grid{grid-template-columns:1fr}.ce-doc-list .item{grid-template-columns:1fr}}
@media print{body.ce-printing>header,body.ce-printing>nav,body.ce-printing main>.page{display:none!important}body.ce-printing main>.page.ce-print-target{display:block!important}body.ce-printing .no-print,body.ce-printing .ce-docbar{display:none!important}body.ce-printing .ce-doc-print{border:0;max-width:none}.ce-doc-print{box-shadow:none}}
`;
document.head.appendChild(s)}
function page(id,title,html){if($(id))return $(id);const s=document.createElement('section');s.id=id;s.className='page';s.innerHTML=`<div class="ce-doc-card"><h1>${title}</h1>${html}</div>`;document.querySelector('main')?.appendChild(s);return s}
function makePages(){
 page('factures-pro','Factures PRO',`<p class="muted">Créez une facture directement ou à partir d’un devis accepté. Les documents sont conservés localement après rechargement.</p><div class="ce-docbar"><button class="primary" data-ce-act="invoice-current">Créer depuis le chiffrage</button><button data-ce-act="print-invoice-list">Imprimer / PDF</button></div><div id="invoiceProList" class="ce-doc-list"></div>`);
 page('demande-particulier','Demande de devis particulier',`<p class="muted">Décrivez votre projet pour transmettre une demande claire à un professionnel. L’estimation indicative existante reste séparée.</p><div class="ce-doc-grid"><div><label>Projet</label><input id="req-project" placeholder="Ex. création d’une terrasse"></div><div><label>Branche</label><select id="req-branch"></select></div><div><label>Prestation</label><select id="req-prest"></select></div><div><label>Quantité</label><input id="req-qty" type="number" step=".01" value="1"></div><div><label>Unité</label><select id="req-unit"><option>forfait</option><option>m²</option><option>mètre</option><option>m³</option><option>heure</option><option>unité</option></select></div><div><label>État des lieux</label><select id="req-state"><option>Bon état</option><option>État courant</option><option>Dégradé</option><option>Très dégradé</option><option>Accès difficile</option></select></div><div><label>Longueur (m)</label><input id="req-l" type="number" step=".01"></div><div><label>Largeur (m)</label><input id="req-w" type="number" step=".01"></div><div><label>Hauteur (m)</label><input id="req-h" type="number" step=".01"></div></div><label>Informations utiles</label><textarea id="req-notes" rows="5" placeholder="Accès, contraintes, photos à transmettre, délai souhaité..."></textarea><div class="ce-docbar"><button class="primary" data-ce-act="save-request">Enregistrer la demande</button></div><div id="requestList" class="ce-doc-list"></div>`);
 page('factures-particulier','Factures particulier',`<p class="muted">Consultez les factures enregistrées et les factures créées à partir d’un devis accepté.</p><div id="invoicePartList" class="ce-doc-list"></div>`);
}
function renderInvoiceHtml(inv){const d=inv.data;return `<div class="ce-doc-print" id="invoice-print"><h1>FACTURE</h1><p><b>${esc(d.entreprise||'Entreprise')}</b><br>N° ${esc(inv.number)} · ${esc(inv.date)}</p><p><b>Client :</b> ${esc(d.client||'—')}</p><div class="line"><span>${esc(d.prest||d.metier||'Prestation')} — ${d.qty||0} ${esc(d.unit||'')}</span><b>${esc(d.ht)}</b></div><div class="line"><span>Main-d’œuvre</span><b>${eur((d.hours||0)*(d.rate||0))}</b></div>${(d.materials||[]).map(x=>`<div class="line"><span>${esc(x)}</span><b></b></div>`).join('')}${(d.tools||[]).map(x=>`<div class="line"><span>${esc(x)}</span><b></b></div>`).join('')}${(d.wastes||[]).map(x=>`<div class="line"><span>${esc(x)}</span><b></b></div>`).join('')}<div class="line"><span>Total HT</span><b>${esc(d.ht)}</b></div><div class="line"><span>TVA ${d.vat||0}%</span><b>${esc(d.ttc&&d.ht?Number(String(d.ttc).replace(/[^0-9,.-]/g,'').replace(',','.'))-Number(String(d.ht).replace(/[^0-9,.-]/g,'').replace(',','.')):0)}</b></div><div class="line"><span>Total TTC</span><b>${esc(d.ttc)}</b></div>${d.eco?`<div class="ce-doc-good"><b>Écologie :</b> tri, réemploi, broyage et/ou optimisation des déplacements selon les choix enregistrés.</div>`:''}</div>`}
function renderInvoices(){const all=load('ce_invoices',[]);const render=(id,mode)=>{const el=$(id);if(!el)return;const arr=mode==='pro'?all.filter(x=>x.origin==='pro'):all;el.innerHTML=arr.length?arr.map((x,i)=>`<div class="item"><span><b>${esc(x.number)}</b> — ${esc(x.data.client||'Sans client')}<br><small>${esc(x.date)} · ${esc(x.data.ttc||'0 €')} · ${x.status==='draft'?'Brouillon':'Émise'}</small></span><span class="ce-docbar"><button data-inv-view="${x.id}">Voir</button><button data-inv-print="${x.id}">PDF</button><button data-inv-del="${x.id}">×</button></span></div>`).join(''):'<p class="muted">Aucune facture enregistrée.</p>'};render('invoiceProList','pro');render('invoicePartList','part');}
function renderRequests(){const el=$('requestList');if(!el)return;const a=load('ce_requests',[]);el.innerHTML=a.length?a.map((x,i)=>`<div class="item"><span><b>${esc(x.project||'Projet')}</b> — ${esc(x.branch)} / ${esc(x.prest)}<br><small>${esc(x.date)} · ${x.qty||0} ${esc(x.unit||'')}</small></span><button data-req-del="${i}">×</button></div>`).join(''):'<p class="muted">Aucune demande enregistrée.</p>';el.querySelectorAll('[data-req-del]').forEach(b=>b.onclick=()=>{if(confirm('Supprimer cette demande ?')){const a=load('ce_requests',[]);a.splice(+b.dataset.reqDel,1);save('ce_requests',a);renderRequests()}})}
function renderQuotesHistory(){const host=$('historique');if(!host||host.querySelector('#ceDocumentHistory'))return;const wrap=document.createElement('div');wrap.id='ceDocumentHistory';wrap.className='ce-doc-card';wrap.innerHTML=`<h2>Documents</h2><div class="ce-doc-toolbar"><input id="ce-doc-search" placeholder="Rechercher client, numéro, prestation..."></div><div id="ce-doc-results"></div>`;host.appendChild(wrap);const draw=()=>{const q=load('ce_quotes',[]),i=load('ce_invoices',[]),r=load('ce_requests',[]),term=($('ce-doc-search')?.value||'').toLowerCase();const docs=[...q.map(x=>({type:'Devis',n:x.number,c:x.data.client,d:x.date,status:x.status,id:x.id})),...i.map(x=>({type:'Facture',n:x.number,c:x.data.client,d:x.date,status:x.status,id:x.id})),...r.map(x=>({type:'Demande',n:'REQ-'+x.id.slice(-6),c:x.project,d:x.date,status:'Enregistrée',id:x.id}))].filter(x=>`${x.type} ${x.n} ${x.c} ${x.d} ${x.status}`.toLowerCase().includes(term));$('ce-doc-results').innerHTML=docs.length?docs.map(x=>`<div class="item"><span><b>${esc(x.type)}</b> · ${esc(x.n)} — ${esc(x.c||'')}<br><small>${esc(x.d)} · ${esc(x.status)}</small></span><span class="ce-docbar"><button data-doc-open="${x.type}|${x.id}">Ouvrir</button><button data-doc-del="${x.type}|${x.id}">×</button></span></div>`).join(''):'<p class="muted">Aucun document trouvé.</p>'};wrap.querySelector('#ce-doc-search').oninput=draw;draw();wrap.addEventListener('click',e=>{const b=e.target.closest('button[data-doc-open],button[data-doc-del]');if(!b)return;const [type,id]=b.dataset.docOpen?.split('|')||b.dataset.docDel?.split('|')||[];if(b.dataset.docDel){if(!confirm('Supprimer ce document ?'))return;const key=type==='Devis'?'ce_quotes':type==='Facture'?'ce_invoices':'ce_requests';const a=load(key,[]);const ix=a.findIndex(x=>x.id===id);if(ix>=0)a.splice(ix,1);save(key,a);draw();renderInvoices();renderRequests();return}if(type==='Devis'){const q=load('ce_quotes',[]).find(x=>x.id===id);if(q){renderQuote(q);window.go?.('devis')}}else if(type==='Facture'){const inv=load('ce_invoices',[]).find(x=>x.id===id);if(inv){renderInvoice(inv,'factures-pro')}}else if(type==='Demande'){window.go?.('demande-particulier')}})}
}
function renderQuote(q){const d=q.data;const el=$('quote');if(!el)return;el.innerHTML=`<h1>DEVIS</h1><p><b>${esc(d.entreprise||'Entreprise')}</b><br>N° ${esc(q.number)} · ${esc(q.date)}</p><p><b>Client :</b> ${esc(d.client||'—')}</p><div class="line"><span>${esc(d.prest||d.metier||'Prestation')} — ${d.qty||0} ${esc(d.unit||'')}</span><b>${esc(d.ht)}</b></div><div class="line"><span>Main-d’œuvre</span><b>${eur((d.hours||0)*(d.rate||0))}</b></div>${(d.materials||[]).map(x=>`<div class="line"><span>${esc(x)}</span><b></b></div>`).join('')}${(d.tools||[]).map(x=>`<div class="line"><span>${esc(x)}</span><b></b></div>`).join('')}${(d.wastes||[]).map(x=>`<div class="line"><span>${esc(x)}</span><b></b></div>`).join('')}<div class="line"><span>Total HT</span><b>${esc(d.ht)}</b></div><div class="line"><span>TVA ${d.vat||0}%</span><b></b></div><div class="line"><span>Total TTC</span><b>${esc(d.ttc)}</b></div>${d.eco?`<div class="ce-doc-good"><b>Écologie :</b> options écologiques enregistrées dans le chiffrage.</div>`:''}<div class="ce-docbar no-print"><button class="primary" data-quote-save="${q.id}">Enregistrer le devis</button>${q.status==='accepted'?`<button data-quote-invoice="${q.id}">Transformer en facture</button>`:`<button data-quote-accept="${q.id}">Accepter le devis</button>`}</div>`;el.querySelectorAll('[data-quote-accept]').forEach(b=>b.onclick=()=>{const a=load('ce_quotes',[]),x=a.find(v=>v.id===q.id);if(x){x.status='accepted';x.acceptedAt=new Date().toLocaleString('fr-FR');save('ce_quotes',a);renderQuote(x)}});el.querySelectorAll('[data-quote-invoice]').forEach(b=>b.onclick=()=>createInvoiceFromQuote(q.id));el.querySelectorAll('[data-quote-save]').forEach(b=>b.onclick=()=>{const a=load('ce_quotes',[]),x=a.find(v=>v.id===q.id);if(x){x.saved=true;save('ce_quotes',a);renderQuote(x)}})}
function createQuote(){try{window.calc?.();const number=ensureNumber();const q={id:crypto.randomUUID?crypto.randomUUID():String(Date.now()),number,date:new Date().toLocaleString('fr-FR'),status:'draft',data:snapshot()};const a=load('ce_quotes',[]);a.unshift(q);save('ce_quotes',a);renderQuote(q);window.go?.('devis');return q}catch(e){console.error('[documents] quote',e)}}
function createInvoiceFromQuote(id){const q=load('ce_quotes',[]).find(x=>x.id===id);if(!q||q.status!=='accepted'){alert('Le devis doit être accepté avant transformation en facture.');return}const inv={id:crypto.randomUUID?crypto.randomUUID():String(Date.now()),number:nextNumber('ce_doc_invoice_sequences','FAC'),date:new Date().toLocaleString('fr-FR'),status:'draft',origin:'pro',sourceQuote:id,data:JSON.parse(JSON.stringify(q.data))};const a=load('ce_invoices',[]);a.unshift(inv);save('ce_invoices',a);renderInvoice(inv,'factures-pro');window.go?.('factures-pro')}
function createInvoiceCurrent(){window.calc?.();const inv={id:crypto.randomUUID?crypto.randomUUID():String(Date.now()),number:nextNumber('ce_doc_invoice_sequences','FAC'),date:new Date().toLocaleString('fr-FR'),status:'draft',origin:'pro',sourceQuote:null,data:snapshot()};const a=load('ce_invoices',[]);a.unshift(inv);save('ce_invoices',a);renderInvoices();renderInvoice(inv,'factures-pro')}
function renderInvoice(inv,target='factures-pro'){const p=$(target);if(!p)return;let area=p.querySelector('#ce-invoice-preview');if(!area){area=document.createElement('div');area.id='ce-invoice-preview';p.appendChild(area)}area.innerHTML=renderInvoiceHtml(inv)+`<div class="ce-docbar no-print"><button class="primary" data-invoice-print="1">Imprimer / PDF</button></div>`;area.querySelector('[data-invoice-print]').onclick=()=>printPage(p)}
function printPage(p){document.querySelectorAll('.page').forEach(x=>x.classList.remove('ce-print-target'));p.classList.add('ce-print-target');document.body.classList.add('ce-printing');window.print();setTimeout(()=>{document.body.classList.remove('ce-printing');p.classList.remove('ce-print-target')},500)}
function particularRequest(){const x={id:crypto.randomUUID?crypto.randomUUID():String(Date.now()),date:new Date().toLocaleString('fr-FR'),project:$('req-project')?.value||'',branch:$('req-branch')?.value||'',prest:$('req-prest')?.value||'',qty:+($('req-qty')?.value||0),unit:$('req-unit')?.value||'',state:$('req-state')?.value||'',dimensions:{l:+($('req-l')?.value||0),w:+($('req-w')?.value||0),h:+($('req-h')?.value||0)},notes:$('req-notes')?.value||''};const a=load('ce_requests',[]);a.unshift(x);save('ce_requests',a);if($('req-project'))$('req-project').value='';if($('req-notes'))$('req-notes').value='';renderRequests()}
function wire(){
 baseCss();makePages();
 const br=$('req-branch');if(br&&$('metier')){br.innerHTML=[...$('metier').options].map(o=>`<option>${esc(o.value)}</option>`).join('');const fill=()=>{const opts=[...($('prest')?.options||[])].map(o=>`<option>${esc(o.value)}</option>`).join('');if($('req-prest'))$('req-prest').innerHTML=opts};br.onchange=()=>{if($('metier')){$('metier').value=br.value;window.profession?.();fill()}};fill()}
 document.querySelectorAll('[data-ce-act="invoice-current"]').forEach(b=>b.onclick=createInvoiceCurrent);
 document.querySelectorAll('[data-ce-act="print-invoice-list"]').forEach(b=>b.onclick=()=>printPage($('factures-pro')));
 document.querySelectorAll('[data-ce-act="save-request"]').forEach(b=>b.onclick=particularRequest);
 document.querySelectorAll('[data-inv-view]').forEach(()=>{});
 ['invoiceProList','invoicePartList'].forEach(id=>$(id)?.addEventListener('click',e=>{const b=e.target.closest('button');if(!b)return;const inv=load('ce_invoices',[]).find(x=>x.id===b.dataset.invView||x.id===b.dataset.invPrint||x.id===b.dataset.invDel);if(!inv)return;if(b.dataset.invView)renderInvoice(inv,b.closest('.page')?.id||'factures-pro');if(b.dataset.invPrint)printPage(b.closest('.page'));if(b.dataset.invDel){if(confirm('Supprimer cette facture ?')){save('ce_invoices',load('ce_invoices',[]).filter(x=>x.id!==inv.id));renderInvoices()}}}));
 renderInvoices();renderRequests();
}
function enhanceNav(){
 const pro=document.querySelector('#pro .ce-page-nav');if(pro&&!pro.querySelector('[data-doc-nav="factures"]')){const b=document.createElement('button');b.textContent='Factures';b.onclick=()=>window.go?.('factures-pro');pro.appendChild(b)}
 const part=document.querySelector('#particulier .ce-page-nav');if(part&&!part.querySelector('[data-doc-nav="request"]')){for(const [text,id] of [['Demande de devis','demande-particulier'],['Factures','factures-particulier']]){const b=document.createElement('button');b.textContent=text;b.onclick=()=>window.go?.(id);part.appendChild(b)}}
 const nav=$('#devis')?.querySelector('.ce-page-nav');if(nav&&!nav.querySelector('[data-doc-nav="invoice"]')){const b=document.createElement('button');b.textContent='Factures';b.onclick=()=>window.go?.('factures-pro');nav.appendChild(b)}
}
function patchMakeQuote(){const original=window.makeQuote;window.makeQuote=()=>createQuote()||original?.()}
if(document.readyState==='loading')document.addEventListener('DOMContentLoaded',()=>setTimeout(()=>{try{wire();enhanceNav();patchMakeQuote()}catch(e){console.error('[documents]',e)}},50),{once:true});else setTimeout(()=>{try{wire();enhanceNav();patchMakeQuote()}catch(e){console.error('[documents]',e)}},50);
})();
