(()=>{
'use strict';
const $=id=>document.getElementById(id);
const esc=s=>String(s??'').replace(/[&<>"']/g,m=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[m]));
const eur=v=>Number(v||0).toLocaleString('fr-FR',{style:'currency',currency:'EUR'});
const load=(k,d=[])=>{try{return JSON.parse(localStorage.getItem(k)||JSON.stringify(d))}catch(_){return d}};
const save=(k,v)=>localStorage.setItem(k,JSON.stringify(v));
const id=()=>crypto.randomUUID?crypto.randomUUID():String(Date.now()+Math.random());
const nextNumber=(key,prefix)=>{const y=new Date().getFullYear();const seq=load(key,{});seq[y]=(seq[y]||0)+1;save(key,seq);return `${prefix}-${y}-${String(seq[y]).padStart(3,'0')}`};
function css(){if($('ce-docs-v2-style'))return;const s=document.createElement('style');s.id='ce-docs-v2-style';s.textContent=`.ce-docbar{display:flex;gap:8px;flex-wrap:wrap;margin-top:12px}.ce-docbar button{padding:10px 13px;border:1px solid var(--line,#d8e3dd);border-radius:9px;background:#fff;font-weight:800;cursor:pointer}.ce-doc-card{background:#fff;border:1px solid var(--line,#d8e3dd);border-radius:15px;padding:18px;margin-bottom:16px}.ce-doc-grid{display:grid;grid-template-columns:repeat(2,minmax(0,1fr));gap:10px}@media(max-width:560px){.ce-doc-grid{grid-template-columns:1fr}.ce-doc-list .item{grid-template-columns:1fr}}@media print{body.ce-printing>header,body.ce-printing>nav,body.ce-printing main>.page{display:none!important}body.ce-printing main>.page.ce-print-target{display:block!important}body.ce-printing .no-print,body.ce-printing .ce-docbar{display:none!important}.ce-doc-print{border:0!important;max-width:none!important;box-shadow:none!important}}`;document.head.appendChild(s)}
function page(id,title,html){let p=$(id);if(p)return p;p=document.createElement('section');p.id=id;p.className='page';p.innerHTML=`<div class="ce-doc-card"><h1>${title}</h1>${html}</div>`;document.querySelector('main')?.appendChild(p);return p}
function snapshot(){const items=id=>[...document.querySelectorAll(`#${id} .item`)].map(x=>x.innerText.trim());return{entreprise:$('entreprise')?.value||'',client:$('client')?.value||'',metier:$('metier')?.value||'',prest:$('prest')?.value||'',etat:$('etat')?.value||'',qty:+($('qty')?.value||0),unit:$('unit')?.value||'',hours:+($('hours')?.value||0),rate:+($('rate')?.value||0),vat:+($('vat')?.value||0),direct:$('cost')?.textContent||'0 €',margin:$('me')?.textContent||'0 €',marginPct:$('mr')?.textContent||'0 %',ht:$('ht')?.textContent||'0 €',ttc:$('ttc')?.textContent||'0 €',materials:items('ml'),tools:items('tl'),wastes:items('wlst'),eco:{sort:!!$('sort')?.checked,reuse:!!$('reuse')?.checked,grind:!!$('grind')?.checked,opt:!!$('opt')?.checked}}}
function renderQuote(q){const d=q.data,e=$('quote');if(!e)return;e.innerHTML=`<h1>DEVIS</h1><p><b>${esc(d.entreprise||'Entreprise')}</b><br>N° ${esc(q.number)} · ${esc(q.date)}</p><p><b>Client :</b> ${esc(d.client||'—')}</p><div class="line"><span>${esc(d.prest||d.metier||'Prestation')} — ${d.qty||0} ${esc(d.unit||'')}</span><b>${esc(d.ht)}</b></div><div class="line"><span>Main-d’œuvre</span><b>${eur((d.hours||0)*(d.rate||0))}</b></div>${(d.materials||[]).map(x=>`<div class="line"><span>${esc(x)}</span></div>`).join('')}${(d.tools||[]).map(x=>`<div class="line"><span>${esc(x)}</span></div>`).join('')}${(d.wastes||[]).map(x=>`<div class="line"><span>${esc(x)}</span></div>`).join('')}<div class="line"><span>Total HT</span><b>${esc(d.ht)}</b></div><div class="line"><span>TVA ${d.vat||0}%</span></div><div class="line"><span>Total TTC</span><b>${esc(d.ttc)}</b></div><div class="ce-docbar no-print"><button class="primary" data-q-save>Enregistrer le devis</button>${q.status==='accepted'?'<button data-q-invoice>Transformer en facture</button>':'<button data-q-accept>Accepter le devis</button>'}</div>`;e.querySelector('[data-q-save]').onclick=()=>{q.saved=true;save('ce_quotes',load('ce_quotes',[]));};const a=e.querySelector('[data-q-accept]');if(a)a.onclick=()=>{q.status='accepted';q.acceptedAt=new Date().toLocaleString('fr-FR');save('ce_quotes',load('ce_quotes',[]));renderQuote(q)};const b=e.querySelector('[data-q-invoice]');if(b)b.onclick=()=>createInvoiceFromQuote(q.id)}
function createQuote(){window.calc?.();let num=$('num')?.value.trim();if(!num){num=nextNumber('ce_doc_sequences','DEV');if($('num'))$('num').value=num}const q={id:id(),number:num,date:new Date().toLocaleString('fr-FR'),status:'draft',data:snapshot()};const a=load('ce_quotes',[]);a.unshift(q);save('ce_quotes',a);renderQuote(q);window.go?.('devis');return q}
function invoiceHtml(inv){const d=inv.data;return `<div class="ce-doc-print"><h1>FACTURE</h1><p><b>${esc(d.entreprise||'Entreprise')}</b><br>N° ${esc(inv.number)} · ${esc(inv.date)}</p><p><b>Client :</b> ${esc(d.client||'—')}</p><div class="line"><span>${esc(d.prest||d.metier||'Prestation')} — ${d.qty||0} ${esc(d.unit||'')}</span><b>${esc(d.ht)}</b></div><div class="line"><span>Main-d’œuvre</span><b>${eur((d.hours||0)*(d.rate||0))}</b></div>${(d.materials||[]).map(x=>`<div class="line"><span>${esc(x)}</span></div>`).join('')}${(d.tools||[]).map(x=>`<div class="line"><span>${esc(x)}</span></div>`).join('')}${(d.wastes||[]).map(x=>`<div class="line"><span>${esc(x)}</span></div>`).join('')}<div class="line"><span>Total HT</span><b>${esc(d.ht)}</b></div><div class="line"><span>TVA ${d.vat||0}%</span></div><div class="line"><span>Total TTC</span><b>${esc(d.ttc)}</b></div></div>`}
function printPage(p){document.querySelectorAll('.page').forEach(x=>x.classList.remove('ce-print-target'));p.classList.add('ce-print-target');document.body.classList.add('ce-printing');window.print();setTimeout(()=>{document.body.classList.remove('ce-printing');p.classList.remove('ce-print-target')},500)}
function renderInvoice(inv,target='factures-pro'){const p=$(target);if(!p)return;let host=p.querySelector('#ce-invoice-preview');if(!host){host=document.createElement('div');host.id='ce-invoice-preview';p.appendChild(host)}host.innerHTML=invoiceHtml(inv)+`<div class="ce-docbar no-print"><button class="primary" data-i-print>Imprimer / PDF</button></div>`;host.querySelector('[data-i-print]').onclick=()=>printPage(p)}
function createInvoiceFromQuote(qid){const q=load('ce_quotes',[]).find(x=>x.id===qid);if(!q||q.status!=='accepted'){alert('Le devis doit être accepté avant transformation en facture.');return}const inv={id:id(),number:nextNumber('ce_doc_invoice_sequences','FAC'),date:new Date().toLocaleString('fr-FR'),status:'draft',origin:'pro',sourceQuote:qid,data:JSON.parse(JSON.stringify(q.data))};const a=load('ce_invoices',[]);a.unshift(inv);save('ce_invoices',a);renderInvoice(inv);window.go?.('factures-pro')}
function currentInvoice(){window.calc?.();const inv={id:id(),number:nextNumber('ce_doc_invoice_sequences','FAC'),date:new Date().toLocaleString('fr-FR'),status:'draft',origin:'pro',sourceQuote:null,data:snapshot()};const a=load('ce_invoices',[]);a.unshift(inv);save('ce_invoices',a);renderInvoices();renderInvoice(inv)}
function renderInvoices(){const all=load('ce_invoices',[]);const fill=(id,pro)=>{const e=$(id);if(!e)return;const arr=pro?all.filter(x=>x.origin==='pro'):all;e.innerHTML=arr.length?arr.map(inv=>`<div class="item"><span><b>${esc(inv.number)}</b> — ${esc(inv.data.client||'Sans client')}<br><small>${esc(inv.date)} · ${esc(inv.data.ttc||'0 €')}</small></span><span class="ce-docbar"><button data-view="${inv.id}">Voir</button><button data-pdf="${inv.id}">PDF</button><button data-del="${inv.id}">×</button></span></div>`).join(''):'<p class="muted">Aucune facture enregistrée.</p>'};fill('invoiceProList',true);fill('invoicePartList',false)}
function requestSave(){const r={id:id(),date:new Date().toLocaleString('fr-FR'),project:$('req-project')?.value||'',branch:$('req-branch')?.value||'',prest:$('req-prest')?.value||'',qty:+($('req-qty')?.value||0),unit:$('req-unit')?.value||'',state:$('req-state')?.value||'',dimensions:{l:+($('req-l')?.value||0),w:+($('req-w')?.value||0),h:+($('req-h')?.value||0)},notes:$('req-notes')?.value||''};const a=load('ce_requests',[]);a.unshift(r);save('ce_requests',a);renderRequests()}
function renderRequests(){const e=$('requestList');if(!e)return;const a=load('ce_requests',[]);e.innerHTML=a.length?a.map((r,i)=>`<div class="item"><span><b>${esc(r.project||'Projet')}</b> — ${esc(r.branch)} / ${esc(r.prest)}<br><small>${esc(r.date)} · ${r.qty||0} ${esc(r.unit||'')}</small></span><button data-r-del="${i}">×</button></div>`).join(''):'<p class="muted">Aucune demande enregistrée.</p>';e.querySelectorAll('[data-r-del]').forEach(b=>b.onclick=()=>{if(confirm('Supprimer cette demande ?')){const x=load('ce_requests',[]);x.splice(+b.dataset.rDel,1);save('ce_requests',x);renderRequests()}})}
function history(){let h=$('historique');if(!h)return;let box=$('ceDocumentHistory');if(box)box.remove();box=document.createElement('div');box.id='ceDocumentHistory';box.className='ce-doc-card';box.innerHTML='<h2>Historique des documents</h2><input id="ce-doc-search" placeholder="Rechercher client, numéro, prestation..." style="width:100%;margin:8px 0"><div id="ce-doc-results"></div>';h.appendChild(box);const draw=()=>{const q=load('ce_quotes',[]),i=load('ce_invoices',[]),r=load('ce_requests',[]),t=($('ce-doc-search').value||'').toLowerCase();const docs=[...q.map(x=>({type:'Devis',n:x.number,c:x.data.client,d:x.date,status:x.status,id:x.id})),...i.map(x=>({type:'Facture',n:x.number,c:x.data.client,d:x.date,status:x.status,id:x.id})),...r.map(x=>({type:'Demande',n:'REQ-'+String(x.id).slice(-6),c:x.project,d:x.date,status:'Enregistrée',id:x.id}))].filter(x=>(`${x.type} ${x.n} ${x.c} ${x.d} ${x.status}`).toLowerCase().includes(t));$('ce-doc-results').innerHTML=docs.length?docs.map(x=>`<div class="item"><span><b>${esc(x.type)}</b> · ${esc(x.n)} — ${esc(x.c||'')}<br><small>${esc(x.d)} · ${esc(x.status)}</small></span><span><button data-open="${x.type}" data-id="${x.id}">Ouvrir</button><button data-remove="${x.type}" data-id="${x.id}">×</button></span></div>`).join(''):'<p class="muted">Aucun document trouvé.</p>'};box.querySelector('#ce-doc-search').oninput=draw;draw();box.addEventListener('click',e=>{const b=e.target.closest('button');if(!b)return;const typ=b.dataset.open||b.dataset.remove,key=typ==='Devis'?'ce_quotes':typ==='Facture'?'ce_invoices':'ce_requests';if(b.dataset.remove){if(!confirm('Supprimer ce document ?'))return;save(key,load(key,[]).filter(x=>x.id!==b.dataset.id));draw();renderInvoices();renderRequests();return}if(typ==='Devis')window.go?.('devis');else if(typ==='Facture')window.go?.('factures-pro');else window.go?.('demande-particulier')})}
function requestPages(){page('factures-pro','Factures PRO',`<p class="muted">Créez une facture depuis le chiffrage ou consultez vos factures enregistrées.</p><div class="ce-docbar"><button class="primary" id="create-invoice-current">Créer depuis le chiffrage</button><button id="print-invoices">Imprimer / PDF</button></div><div id="invoiceProList" class="ce-doc-list"></div>`);page('demande-particulier','Demande de devis particulier',`<p class="muted">Décrivez votre projet pour transmettre une demande claire à un professionnel. L’estimation indicative existante reste conservée.</p><div class="ce-doc-grid"><div><label>Projet</label><input id="req-project"></div><div><label>Branche</label><select id="req-branch"></select></div><div><label>Prestation</label><select id="req-prest"></select></div><div><label>Quantité</label><input id="req-qty" type="number" step=".01" value="1"></div><div><label>Unité</label><select id="req-unit"><option>forfait</option><option>m²</option><option>mètre</option><option>m³</option><option>heure</option><option>unité</option></select></div><div><label>État des lieux</label><select id="req-state"><option>Bon état</option><option>État courant</option><option>Dégradé</option><option>Très dégradé</option><option>Accès difficile</option></select></div><div><label>Longueur (m)</label><input id="req-l" type="number" step=".01"></div><div><label>Largeur (m)</label><input id="req-w" type="number" step=".01"></div><div><label>Hauteur (m)</label><input id="req-h" type="number" step=".01"></div></div><label>Informations utiles</label><textarea id="req-notes" rows="5"></textarea><div class="ce-docbar"><button class="primary" id="save-request">Enregistrer la demande</button></div><div id="requestList" class="ce-doc-list"></div>`);page('factures-particulier','Factures particulier','<p class="muted">Consultez les factures enregistrées.</p><div id="invoicePartList" class="ce-doc-list"></div>')}
function wire(){css();requestPages();const rb=$('req-branch');if(rb&&$('metier')){rb.innerHTML=[...$('metier').options].map(o=>`<option value="${esc(o.value)}">${esc(o.value)}</option>`).join('');const fill=()=>{if($('req-prest'))$('req-prest').innerHTML=[...($('prest')?.options||[])].map(o=>`<option value="${esc(o.value)}">${esc(o.value)}</option>`).join('')};rb.onchange=()=>{if($('metier')){$('metier').value=rb.value;window.profession?.();fill()}};fill()}
$('create-invoice-current').onclick=currentInvoice;$('print-invoices').onclick=()=>printPage($('factures-pro'));$('save-request').onclick=requestSave;renderInvoices();renderRequests();
['invoiceProList','invoicePartList'].forEach(list=>$(list)?.addEventListener('click',e=>{const b=e.target.closest('button');if(!b)return;const inv=load('ce_invoices',[]).find(x=>x.id===b.dataset.view||x.id===b.dataset.pdf||x.id===b.dataset.del);if(!inv)return;if(b.dataset.view)renderInvoice(inv,b.closest('.page').id);if(b.dataset.pdf)printPage(b.closest('.page'));if(b.dataset.del){if(confirm('Supprimer cette facture ?')){save('ce_invoices',load('ce_invoices',[]).filter(x=>x.id!==inv.id));renderInvoices()}}}));
if($('metier')&&$('prest')){const fill=()=>{if($('req-prest'))$('req-prest').innerHTML=[...$('prest').options].map(o=>`<option>${esc(o.value)}</option>`).join('')};$('metier').addEventListener('change',fill);fill()}
const pro=document.querySelector('#pro .ce-page-nav');if(pro&&!pro.querySelector('[data-doc-v2="factures"]')){const b=document.createElement('button');b.textContent='Factures';b.dataset.docV2='factures';b.onclick=()=>window.go?.('factures-pro');pro.appendChild(b)}const part=document.querySelector('#particulier .ce-page-nav');if(part&&!part.querySelector('[data-doc-v2="request"]')){[['Demande de devis','demande-particulier'],['Factures','factures-particulier']].forEach(([label,target])=>{const b=document.createElement('button');b.textContent=label;b.dataset.docV2=label;b.onclick=()=>window.go?.(target);part.appendChild(b)})}}
function patchQuote(){window.makeQuote=createQuote}
function init(){wire();patchQuote();const g=window.go;window.go=(target)=>{const r=g?.(target);if(target==='historique')setTimeout(history,0);return r};setTimeout(()=>{const pro=document.querySelector('#pro .ce-page-nav');const part=document.querySelector('#particulier .ce-page-nav');if(pro&&!pro.querySelector('[data-doc-v2="factures"]'))wire();if(part&&!part.querySelector('[data-doc-v2="request"]'))wire()},150)}
if(document.readyState==='loading')document.addEventListener('DOMContentLoaded',()=>setTimeout(init,80),{once:true});else setTimeout(init,80);
})();