(()=>{
  'use strict';
  const fixHomeLayout=()=>{
    if(document.getElementById('ce-home-layout-fix'))return;
    const img=document.querySelector('.home img');if(img)img.src='./file_00000000cef88246bb6203174d2ac629.png';
    const style=document.createElement('style');style.id='ce-home-layout-fix';style.textContent=`html,body{max-width:100%;overflow-x:hidden!important}.home{position:relative!important;width:100%!important;max-width:100%!important;min-height:520px!important;overflow:hidden!important;background:#fff!important;border-radius:20px!important}.home>img{display:block!important;width:100%!important;max-width:100%!important;height:auto!important;min-width:0!important;object-fit:contain!important;object-position:center top!important}.home-offers{position:absolute!important;left:3%!important;right:3%!important;bottom:3%!important;display:grid!important;grid-template-columns:1fr 1fr!important;gap:16px!important;z-index:5!important}.home-offer{display:block!important;background:rgba(255,255,255,.96)!important;border:2px solid #d8e3dd!important;border-radius:16px!important;padding:16px!important;box-shadow:0 8px 24px rgba(16,60,44,.16)!important}.home-offer-title,.home-price,.home-offer-text{display:block!important}.home-offer-btn{display:block!important;width:100%!important;background:#146b4a!important;color:#fff!important;border:0!important;border-radius:10px!important;min-height:44px!important;font-weight:900!important}.home-copy{display:block!important}.home-links{display:none!important}@media(max-width:560px){.home{min-height:600px!important}.home-offers{left:3%!important;right:3%!important;bottom:3%!important;gap:10px!important}.home-offer{padding:12px!important}.home-offer-title{font-size:18px!important}.home-price{font-size:22px!important}.home-offer-text{font-size:12px!important}.home-offer-btn{min-height:42px!important}}`;document.head.appendChild(style);
  };
  const loadScript=(src,attr)=>new Promise(resolve=>{if(document.querySelector(`script[src="${src}"]`))return resolve();const s=document.createElement('script');s.src=src;if(attr)Object.assign(s,attr);s.defer=true;s.onload=resolve;s.onerror=resolve;document.head.appendChild(s)});
  const start=async()=>{fixHomeLayout();await loadScript('./runtime-stability.js',{'data-ce-runtime':'1'});await loadScript('./navigation-v2.js',{'data-ce-navigation':'1'});await loadScript('./documents-v2.js',{'data-ce-documents':'1'});await loadScript('./barometre-pro-v1.js',{'data-ce-barometre':'1'});await loadScript('./workflow-particulier-v1.js',{'data-ce-part-workflow':'1'});await loadScript('./navigation-bridge-v1.js',{'data-ce-navigation-bridge':'1'});await loadScript('./document-access-v1.js',{'data-ce-document-access':'1'});await loadScript('./document-workflow-access-v2.js',{'data-ce-doc-access-v2':'1'});window.__ceNavigationRefresh?.();if(!('serviceWorker'in navigator))return;try{const reg=await navigator.serviceWorker.register('./sw.js',{updateViaCache:'none'});await reg.update()}catch(error){console.warn('Chiffr’EcoPro PWA indisponible :',error)}};
  if(document.readyState==='loading')document.addEventListener('DOMContentLoaded',start,{once:true});else start();
})();
