(()=>{
  'use strict';
  const fixHomeLayout=()=>{
    if(document.getElementById('ce-home-layout-fix'))return;
    const img=document.querySelector('.home img');if(img){img.onerror=()=>{img.onerror=null}}
    const style=document.createElement('style');style.id='ce-home-layout-fix';style.textContent=`html,body{max-width:100%;overflow-x:hidden!important}.home{position:relative!important;display:block!important;width:100%!important;max-width:100%!important;height:auto!important;min-height:0!important;overflow:hidden!important;background:#fff!important;border-radius:20px!important;line-height:0!important}.home>img{display:block!important;width:100%!important;max-width:100%!important;height:auto!important;min-width:0!important;object-fit:contain!important;object-position:center top!important}.home-links{position:absolute!important;left:3.2%!important;right:3.2%!important;bottom:6.5%!important;width:auto!important;height:12%!important;padding:0!important;margin:0!important;background:transparent!important;display:grid!important;grid-template-columns:1fr 1fr!important;gap:3%!important;z-index:5!important}.home-links button{display:block!important;width:100%!important;height:100%!important;min-height:44px!important;border:0!important;border-radius:16px!important;background:transparent!important;color:transparent!important;font-size:0!important;line-height:0!important;box-shadow:none!important;cursor:pointer!important;padding:0!important;opacity:.01!important}.home-links button:active{transform:none!important}.home-copy{display:block!important}@media(max-width:560px){.home{height:auto!important;min-height:0!important}.home>img{width:100%!important;height:auto!important;object-fit:contain!important}.home-links{left:3%!important;right:3%!important;bottom:6%!important;height:12%!important;gap:3%!important}}`;document.head.appendChild(style);
  };
  const loadScript=(src,attr)=>new Promise(resolve=>{if(document.querySelector(`script[src="${src}"]`))return resolve();const s=document.createElement('script');s.src=src;if(attr)Object.assign(s,attr);s.defer=true;s.onload=resolve;s.onerror=resolve;document.head.appendChild(s)});
  const start=async()=>{fixHomeLayout();await loadScript('./runtime-stability.js',{'data-ce-runtime':'1'});await loadScript('./navigation-v2.js',{'data-ce-navigation':'1'});await loadScript('./documents-v2.js',{'data-ce-documents':'1'});await loadScript('./barometre-pro-v1.js',{'data-ce-barometre':'1'});await loadScript('./workflow-particulier-v1.js',{'data-ce-part-workflow':'1'});await loadScript('./navigation-bridge-v1.js',{'data-ce-navigation-bridge':'1'});await loadScript('./document-access-v1.js',{'data-ce-document-access':'1'});await loadScript('./document-workflow-access-v2.js',{'data-ce-doc-access-v2':'1'});window.__ceNavigationRefresh?.();if(!('serviceWorker'in navigator))return;try{const reg=await navigator.serviceWorker.register('./sw.js',{updateViaCache:'none'});await reg.update()}catch(error){console.warn('Chiffr’EcoPro PWA indisponible :',error)}};
  if(document.readyState==='loading')document.addEventListener('DOMContentLoaded',start,{once:true});else start();
})();
