(()=>{
/* Chifr’Eco&Pro — UX V1 : simple à l'entrée, complet à la demande. */
const UX='1.4';
function installUX(){
 if(document.getElementById('uxStyle'))return;
 const st=document.createElement('style');st.id='uxStyle';st.textContent='.uxbar{display:flex;gap:8px;flex-wrap:wrap;margin:0 0 16px}.uxbar button{border:1px solid #cbd8d1;background:#fff;border-radius:10px;padding:11px 14px;font-weight:850;cursor:pointer}.uxbar .uxprimary{background:#146b4a;color:#fff;border-color:#146b4a}.uxhint{font-size:13px;color:#64736b;margin-top:6px}.uxquick{display:grid;grid-template-columns:repeat(3,1fr);gap:10px;margin-top:14px}.uxquick button{min-height:72px;border:1px solid #d8e3dd;background:#fff;border-radius:13px;padding:12px;text-align:left;font-weight:850}.uxquick small{display:block;color:#64736b;font-weight:500;margin-top:4px}.ceBrand{line-height:.88;letter-spacing:-1px;display:flex!important;flex-direction:column;align-items:flex-start}.ceBrandTop{font-size:1em;font-weight:950}.ceBrandBottom{font-size:.72em;font-weight:950;margin-top:5px;letter-spacing:-.5px}.ceDrop{border:1px solid #d8e3dd;border-radius:12px;padding:12px;margin:8px 0;background:#fff}.ceFree{display:inline-block;background:#e7f6ec;border:1px solid #bddfc8;border-radius:99px;padding:4px 8px;font-size:12px;font-weight:800}.ceWarn{background:#fff5d6;border:1px solid #eed47b;padding:10px;border-radius:9px;font-size:13px}@media(max-width:650px){.uxquick{grid-template-columns:1fr}.uxbar button{flex:1 1 45%}.ceBrandTop{font-size:.92em}.ceBrandBottom{font-size:.67em}}';
 document.head.appendChild(st);
 document.title='Chifr’Eco&Pro — V14';
 document.querySelectorAll('.pill').forEach(x=>{if(x.textContent.trim()==='VERSION 6'||x.textContent.trim()==='VERSION 13')x.textContent='VERSION 14'});
 const logo=document.querySelector('header .logo');
 if(logo&&!logo.dataset.ceBrand){logo.classList.add('ceBrand');logo.dataset.ceBrand='1';logo.textContent='';const top=document.createElement('span');top.className='ceBrandTop';top.textContent='Chifr’';const bottom=document.createElement('span');bottom.className='ceBrandBottom';bottom.textContent='Eco&Pro';logo.append(top,bottom)}
 const home=document.getElementById('accueil');if(home){const card=home.querySelector('.card');if(card&&!document.getElementById('uxQuick')){const q=document.createElement('div');q.id='uxQuick';q.className='uxquick';q.innerHTML='<button onclick="go(\'pro\')">👷 <b>Chiffrer un chantier</b><small>PRO · prix, marge, machines, déchets et devis</small></button><button onclick="go(\'particulier\')">🏠 <b>Estimer mes travaux</b><small>Particulier · estimation simple et comparaison</small></button><button onclick="go(\'eco\')">🌱 <b>Optimiser l’écologie</b><small>Tri, réemploi, broyage, transport et score</small></button>';card.appendChild(q)}}
 const pro=document.getElementById('pro');if(pro&&!document.getElementById('uxProIntro')){const first=pro.firstElementChild;const d=document.createElement('div');d.id='uxProIntro';d.className='uxbar';d.innerHTML='<button class="uxprimary" onclick="document.getElementById(\'metier\').focus()">1️⃣ Métier</button><button onclick="document.getElementById(\'hours\').focus()">2️⃣ Main-d’œuvre</button><button onclick="document.getElementById(\'tn\').focus()">3️⃣ Machines</button><button onclick="document.getElementById(\'wt\').focus()">4️⃣ Évacuation</button><button class="uxprimary" onclick="calc();makeQuote()">📄 Calculer le devis</button>';pro.insertBefore(d,first.nextSibling)}
 const tc=document.getElementById('tc');if(tc){tc.readOnly=true;tc.placeholder='Calcul automatique'}
 const rate=document.getElementById('rate');if(rate&&!document.getElementById('rateHint')){const h=document.createElement('div');h.id='rateHint';h.className='uxhint';h.textContent='Le taux horaire est ajustable. Les machines sont calculées automatiquement.';rate.parentNode.appendChild(h)}
 const margin=document.getElementById('margin');if(margin&&!document.getElementById('marginHint')){const h=document.createElement('div');h.id='marginHint';h.className='uxhint';h.textContent='Marge proposée automatiquement selon le métier · modifiable à tout moment.';margin.parentNode.appendChild(h)}
 const ids=['entreprise','num','client','metier','prest','etat','qty','unit','hours','rate','travel','other','margin','vat'];
 const saveDraft=()=>{try{const o={};ids.forEach(id=>{const e=document.getElementById(id);if(e)o[id]=e.value});localStorage.setItem('ce_draft',JSON.stringify(o))}catch(e){}};
 const loadDraft=()=>{try{const o=JSON.parse(localStorage.getItem('ce_draft')||'{}');if(o.entreprise||o.client||o.num){ids.forEach(id=>{const e=document.getElementById(id);if(e&&o[id]!=null)e.value=o[id]});if(typeof profession==='function')profession()}}catch(e){}};
 loadDraft();ids.forEach(id=>document.getElementById(id)?.addEventListener('input',saveDraft));
}
function installDropOffFinder(){
 if(document.getElementById('dropOffNav'))return;
 const nav=document.querySelector('nav'),main=document.querySelector('main');if(!nav||!main)return;
 const b=document.createElement('button');b.id='dropOffNav';b.textContent='♻️ Dépôts gratuits PRO';b.onclick=()=>{document.querySelectorAll('.page').forEach(x=>x.classList.remove('active'));document.getElementById('dropOffPage').classList.add('active');document.querySelectorAll('nav button').forEach(x=>x.classList.remove('active'));b.classList.add('active')};nav.appendChild(b);
 const q=document.createElement('section');q.id='dropOffPage';q.className='page';q.innerHTML='<div class="card"><span class="pill">ÉCONOMIE D’ÉVACUATION</span><h1>♻️ Dépôts gratuits pour professionnels</h1><p class="muted">Le système privilégie les points de reprise dont la gratuité pour les professionnels est confirmée par la filière. Il vérifie toujours les conditions avant de présenter une solution comme gratuite.</p><div class="ceWarn"><b>Marseille / Aix-Marseille-Provence :</b> les déchèteries métropolitaines publiques n’acceptent plus les professionnels depuis le 1er juillet 2025. Elles ne seront donc pas proposées comme dépôts gratuits PRO.</div><div id="dropOffList"></div><div class="actions"><button class="primary" onclick="window.open(\'https://ecomaison.com/professionnels/services-de-collecte-et-reprise/nos-solutions-decollecte-et-reprise/\',\'_blank\')">Trouver les points Ecomaison</button><button onclick="window.open(\'https://pro.ecosystem.eco/profil/producteur/collecte-producteurs\',\'_blank\')">Points ecosystem PRO</button></div></div>';main.appendChild(q);
 const data=[['🏗️ Déchets du bâtiment triés','Bois, métaux, plastiques, plâtre, menuiseries vitrées, laines minérales et inertes selon le point','Gratuit sous conditions','Tri préalable + point partenaire agréé','Ecomaison / REP PMCB'],['🪑 Mobilier professionnel','Mobilier professionnel usagé pris en charge par la filière','Gratuit sous conditions','Carte Pro, point référencé et limites propres au site','Ecomaison'],['💡 Équipements électriques / lampes','EEE, lampes et tubes dans les points professionnels concernés','Gratuit sous conditions','Quantités et conditions d’accès du point professionnel','ecosystem']];
 document.getElementById('dropOffList').innerHTML=data.map(x=>'<div class="ceDrop"><b>'+x[0]+'</b><p>'+x[1]+'</p><span class="ceFree">'+x[2]+'</span><p class="muted"><b>Conditions :</b> '+x[3]+'<br><b>Filière :</b> '+x[4]+'</p></div>').join('');
}
if(document.readyState==='loading')document.addEventListener('DOMContentLoaded',()=>{installUX();installDropOffFinder()});else{installUX();installDropOffFinder()}
})();
