const { test, expect } = require('@playwright/test');
const url='http://127.0.0.1:4173/index.html';
const hero='./file_00000000cef88246bb6203174d2ac629.png';
async function openFresh(page){await page.goto(url,{waitUntil:'networkidle'});await expect(page.locator('#accueil')).toBeVisible()}
async function go(page,id){await page.locator(`nav button[data-p="${id}"]`).click();await expect(page.locator(`#${id}`)).toBeVisible()}

async function visibleNavTexts(page){return page.locator('nav[aria-label="Navigation principale"] button').evaluateAll(bs=>bs.filter(b=>getComputedStyle(b).display!=='none').map(b=>b.textContent.trim()))}

test('home desktop mobile and no runtime error',async({page,request})=>{const errors=[];page.on('pageerror',e=>errors.push(String(e)));await openFresh(page);await expect(page.locator('.home img')).toHaveAttribute('src',hero);await expect(page.locator('.home-copy')).toBeHidden();await expect(page.locator('.home-links button')).toHaveCount(2);const r=await request.get(`http://127.0.0.1:4173/${hero.slice(2)}`);expect(r.ok()).toBeTruthy();await page.setViewportSize({width:390,height:844});const m=await page.locator('.home img').evaluate(el=>({w:el.clientWidth,h:el.clientHeight,nw:el.naturalWidth,nh:el.naturalHeight}));expect(Math.abs(m.w/m.h-m.nw/m.nh)).toBeLessThan(.02);await page.setViewportSize({width:1280,height:900});expect(errors).toEqual([])});

test('desktop mobile UI harmony and no horizontal page overflow',async({page})=>{await openFresh(page);for(const size of [{width:1280,height:900},{width:390,height:844}]){await page.setViewportSize(size);for(const id of ['pro','particulier','eco','aides','param']){await go(page,id);const layout=await page.locator('body').evaluate(()=>({sw:document.documentElement.scrollWidth,cw:document.documentElement.clientWidth}));expect(layout.sw).toBeLessThanOrEqual(layout.cw+1);await expect(page.locator(`#${id} h1`).first()).toBeVisible();await expect(page.locator(`#${id} .card`).first()).toBeVisible();}await go(page,'pro');const nav=page.locator('#pro .ce-page-nav');const st=await nav.evaluate(e=>({wrap:getComputedStyle(e).flexWrap,white:getComputedStyle(e).whiteSpace}));expect(st.wrap).toBe('nowrap');expect(st.white).toBe('nowrap');const minHeight=await nav.locator('button').first().evaluate(e=>parseFloat(getComputedStyle(e).minHeight)||0);expect(minHeight).toBeGreaterThanOrEqual(size.width<560?38:40);}});

test('primary menu plus visible invoices and mobile horizontal menus',async({page})=>{await openFresh(page);const nav=page.locator('nav[aria-label="Navigation principale"]');expect(await visibleNavTexts(page)).toEqual(['Accueil','Professionnel','Particulier','Factures','🌱 Écologie','Aides / Informations','Compte / Paramètres']);for(const id of ['accueil','pro','particulier','factures-pro','eco','aides','param']){await expect(nav.locator(`button[data-p="${id}"]`)).toBeVisible()}await page.setViewportSize({width:390,height:844});const n=await nav.evaluate(e=>({wrap:getComputedStyle(e).flexWrap,scroll:e.scrollWidth,client:e.clientWidth}));expect(n.wrap).toBe('nowrap');expect(n.scroll).toBeGreaterThan(n.client);await go(page,'pro');const pn=page.locator('#pro .ce-page-nav');const p=await pn.evaluate(e=>({wrap:getComputedStyle(e).flexWrap,white:getComputedStyle(e).whiteSpace,scroll:e.scrollWidth,client:e.clientWidth}));expect(p.wrap).toBe('nowrap');expect(p.white).toBe('nowrap');expect(p.scroll).toBeGreaterThan(p.client);expect(new Set(await pn.locator('button').allTextContents()).size).toBe(await pn.locator('button').count());await go(page,'particulier');const pp=page.locator('#particulier .ce-page-nav');expect(new Set(await pp.locator('button').allTextContents()).size).toBe(await pp.locator('button').count());await go(page,'factures-pro');await expect(page.locator('#factures-pro')).toContainText('Factures PRO')});

test('professional quote materials tools waste metrics',async({page})=>{await openFresh(page);await page.locator('.home-links button').first().click();await page.locator('#client').fill('Client QA');await page.locator('#hours').fill('3');await page.locator('#rate').fill('25');await page.locator('#mn').fill('Terreau');await page.locator('#mq').fill('2');await page.locator('#mp').fill('15');await page.getByRole('button',{name:'Ajouter',exact:true}).nth(0).click();await page.locator('#th').fill('2');await page.getByRole('button',{name:'Ajouter',exact:true}).nth(1).click();await page.locator('#wl').fill('2');await page.locator('#ww').fill('1');await page.locator('#wh').fill('.5');await page.getByRole('button',{name:'Calculer le volume'}).click();await expect(page.locator('#wvol')).toHaveText('1.00 m³');await page.getByRole('button',{name:'Ajouter au chiffrage'}).click();await page.locator('#wmode').selectOption('volume');await page.locator('#wv').fill('3.25');await page.getByRole('button',{name:'Calculer le volume'}).click();await expect(page.locator('#wvol')).toHaveText('3.25 m³');await page.getByRole('button',{name:'Calculer le prix'}).click();await expect(page.locator('#res')).toBeVisible();await expect(page.locator('#ht')).not.toHaveText('');await expect(page.locator('#ttc')).not.toHaveText('')});

test('professional barometer visible and functional in costing',async({page})=>{await openFresh(page);await page.locator('.home-links button').first().click();await expect(page.locator('#ceBarometre')).toBeVisible();await expect(page.locator('#ceBaroCoef')).toContainText('×');await expect(page.locator('#ceBaroHours')).toContainText('h');await page.locator('#hours').fill('4');await page.locator('#rate').fill('30');await page.locator('#etat').selectOption({label:'Accès difficile'});await expect(page.locator('#ceBaroCoef')).not.toHaveText('1,00×');await expect(page.locator('#ceBaroLevel')).toContainText('DIFFICILE');await expect(page.locator('#ceBaroRange')).toContainText('€ HT');await expect(page.locator('#ceBaroWhy')).toContainText('état du site');await page.getByRole('button',{name:'Calculer le prix'}).click();await expect(page.locator('#ht')).not.toHaveText('');});

test('devis accept facture history flow',async({page})=>{await openFresh(page);await page.locator('.home-links button').first().click();await page.locator('#client').fill('Client Doc');await page.locator('#hours').fill('2');await page.locator('#rate').fill('30');await page.getByRole('button',{name:'Calculer le prix'}).click();await page.getByRole('button',{name:'Préparer le devis'}).click();await expect(page.locator('#devis')).toBeVisible();await page.getByRole('button',{name:'Accepter le devis'}).click();await page.getByRole('button',{name:'Transformer en facture'}).click();await expect(page.locator('#factures-pro')).toBeVisible();await expect(page.locator('#factures-pro')).toContainText('FACTURE');expect(await page.evaluate(()=>JSON.parse(localStorage.getItem('ce_quotes')||'[]').length)).toBe(1);expect(await page.evaluate(()=>JSON.parse(localStorage.getItem('ce_invoices')||'[]').length)).toBe(1);await page.reload({waitUntil:'networkidle'});await go(page,'pro');await page.locator('#pro .ce-page-nav button',{hasText:'Factures'}).click();await expect(page.locator('#invoiceProList .item')).toHaveCount(1);await go(page,'pro');await page.locator('#pro .ce-page-nav button',{hasText:'Devis'}).click();await page.locator('#devis .ce-page-nav button',{hasText:'Historique'}).click();await expect(page.locator('#historique')).toBeVisible();await expect(page.locator('#ceDocumentHistory')).toContainText('Devis');await expect(page.locator('#ce-doc-results')).toContainText('Facture')});

test('particular full estimate request quote invoice history flow',async({page})=>{await openFresh(page);await go(page,'particulier');await page.locator('#pq').fill('20');await page.locator('#pd').selectOption('Difficile');await page.getByRole('button',{name:"Obtenir l'estimation"}).click();await expect(page.locator('#pr')).toBeVisible();await page.locator('#particulier .ce-page-nav button',{hasText:'Demande de devis'}).click();await expect(page.locator('#demande-particulier')).toBeVisible();await page.locator('#req-project').fill('Création terrasse');await page.locator('#req-qty').fill('25');await page.getByRole('button',{name:'Enregistrer la demande'}).click();await expect(page.locator('#ce-part-workflow')).toBeVisible();await page.getByRole('button',{name:'Préparer le devis'}).click();await expect(page.locator('#ce-part-workflow')).toContainText('Devis particulier');await page.getByRole('button',{name:'Accepter le devis'}).click();await page.getByRole('button',{name:'Créer la facture'}).click();await page.locator('#particulier .ce-page-nav button',{hasText:'Factures'}).click();await expect(page.locator('#factures-particulier')).toBeVisible();await expect(page.locator('#invoicePartList .item')).toHaveCount(1);await page.locator('#invoicePartList button[data-part-view]').click();await expect(page.locator('#ce-part-invoice-preview')).toContainText('FACTURE PARTICULIER');await page.locator('#particulier .ce-page-nav button',{hasText:'Historique'}).click();await expect(page.locator('#historique')).toBeVisible();await expect(page.locator('#ce-part-history')).toContainText('Devis particulier');await expect(page.locator('#ce-part-history')).toContainText('Facture particulière')});

test('ecology partners aids settings and no page errors',async({page})=>{const errors=[];page.on('pageerror',e=>errors.push(String(e)));await openFresh(page);await go(page,'eco');await expect(page.locator('#score')).toBeVisible();await page.locator('#eco .ce-tools-nav button',{hasText:'Partenaires'}).click();await expect(page.locator('#partnersPage')).toBeVisible();await go(page,'aides');await expect(page.locator('#aid')).not.toHaveText('');await go(page,'param');await expect(page.locator('#dn')).toBeVisible();expect(errors).toEqual([])});

test('PWA reload remains usable',async({page})=>{await openFresh(page);await page.reload({waitUntil:'networkidle'});await expect(page.locator('#accueil')).toBeVisible();expect(await page.evaluate(async()=>('serviceWorker'in navigator)?!!(await navigator.serviceWorker.ready).active:false)).toBeTruthy()});
