name: Deploy Chiffr’EcoPro to OVH

on:
  push:
    branches: [main]
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Deploy to OVH SFTP
        uses: wlixcc/SFTP-Deploy-Action@v1.2.6
        with:
          server: ftp.cluster129.hosting.ovh.net
          port: 22
          username: chiffri
          password: ${{ secrets.OVH_FTP_PASSWORD }}
          sftp_only: true
          local_path: './*'
          remote_path: './www/'
          sftpArgs: '-o ConnectTimeout=10'
